# Generated by Django 4.0.1 on 2022-01-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
