# Generated by Django 4.0.1 on 2022-02-02 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_remove_student_first_name_remove_student_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('sign', models.ImageField(blank=True, default='images/avatar.jpg', upload_to='images/%Y/%m/%d')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='paid_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='08090989808',
                                   max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='ref',
            field=models.CharField(default='REFERENCE NUM', max_length=500, null=True),
        ),
    ]
