# Generated by Django 4.0.1 on 2022-02-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_department_student_paid_student_paid_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatar.jpg', upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='department',
            name='short_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.CharField(default='TESA', max_length=500, null=True),
        ),
    ]
