# Generated by Django 4.0.1 on 2022-02-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_department_avatar_department_short_name_student_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='paid_date',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
