# Generated by Django 4.0.1 on 2022-02-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0006_alter_student_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='paid_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
