# Generated by Django 4.0.1 on 2022-02-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0007_alter_student_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
