# Generated by Django 4.0.1 on 2022-02-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0009_student_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='paid',
        ),
        migrations.AddField(
            model_name='student',
            name='paid_basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='paid_conference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='paid_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='purpose',
            field=models.CharField(default='BASIC DUES', max_length=150, null=True),
        ),
    ]
