# Generated by Django 4.0.1 on 2022-02-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0010_remove_student_paid_student_paid_basic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
