# Generated by Django 4.0.1 on 2022-02-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0011_alter_student_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='purpose',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
